restore setCreator
openspout/openspout pull request #287
Opened 2024-11-29 14:04 UTC by lekoala

this will also require Properties to not be readonly

fixes https://github.com/openspout/openspout/issues/286

2024-11-29 14:06 UTC, Slamdunk requested changes

2024-11-29 14:06 UTC, Slamdunk commented on src/Writer/XLSX/Properties.php
> +final class Properties
This is not needed, just overwrite the object with a new one

2024-11-29 14:06 UTC, Slamdunk commented on src/Writer/XLSX/Writer.php
> +    public function setCreator(string $creator): void
I guess we also need to restore this in the `WriterInterface`

2024-11-30 07:08 UTC, lekoala commented
@Slamdunk kept it readonly (it's just a bit verbose imho), added back method to interface. instead of implementing in abstract, i kept an abstract method and added a noop function to the csv writer

2024-11-30 08:30 UTC, Slamdunk requested changes

2024-11-30 08:30 UTC, Slamdunk commented on src/Writer/AbstractWriter.php
> +    abstract public function setCreator(string $creator): void;
This is already enforced by the interface and can be dropped here

2024-11-30 08:30 UTC, Slamdunk commented on src/Writer/CSV/Writer.php
> +        // noop
May it would be better to raise an Exception message like `Method unsopported for CSV documents`

2024-12-05 13:22 UTC, lekoala commented
@Slamdunk i've made the requested changes

i'm not planning on updating this pr further than that, it feels like you would spend as much time writing the comment as doing the change yourself which seem counterproductive. my proposal would be to merge as is and make any last changes as you see fit.

have a great day,

2024-12-05 13:28 UTC, Slamdunk commented
> it feels like you would spend as much time writing the comment as doing the change yourself which seem counterproductive

It depends on the definition of counterproductive.
I review PR on the open source projects I maintain to share my knowledge so that the knowledge itself can improve for everyone from anyone has better ideas and suggestions.

If you feel annoyed by my feedbacks, imagine how I feel having to deal with hundreds of people like you after I spent my free time in the pursuit of reciprocal help.

2024-12-05 13:33 UTC, Slamdunk approved these changes

2024-12-05 13:34 UTC, merged