row height
openspout/openspout pull request #77
Opened 2022-04-26 12:13 UTC by jonnott

I'm trying to add support for setting row height, but I don't know how to do it.

I've re-added getter/setter and a property which were removed in a recent commit due to being unused. I've also added a failing test.

What I don't know is what the syntax in the raw XML output (XLS or ODS) would be for specifying the height of the row, or where this code would need to be.

The code would check for strlen() of the height property, and then apply the height to the row if height has been set via the setter.

I recently did a PR for celllVerticalAlignment and explicit setWrapText to false: https://github.com/openspout/openspout/pull/63

I'm trying to replicate doing something like this equivalent in XLSXWriter:

```
if ($lines > 1) { $row_options['height'] = $lines * 12.1; }
$writer->writeSheetRow('Sheet1', array_values($row), $row_options);
```

Any help or pointers would be much appreciated. I'd be happy to fully finish this PR and tests if only I knew how!

2022-04-26 12:30 UTC, Slamdunk requested changes
Implementing the feature is the easiest part, we need the test first.

> What I don't know is what the syntax in the raw XML output (XLS or ODS) would be for specifying the height of the row

That's pretty easy to look for: both XLSX and ODS are just a `zip` file of XMLs, so:

1. open LibreOffice/MSOffice
2. write a cell
3. save the document as XLSX/ODS
4. change the height of a row
5. save the document as XLSX/ODS with a different filename
6. rename the files appending `.zip` at the end
7. unzip the files
8. use programs like `meld` or `winmerge` to inspect the two folders

You'll exactly see how the custom row height is written

2022-04-28 15:43 UTC, jonnott commented
> Implementing the feature is the easiest part, we need the test first.

I've updated with a working implementation and passing test for XLSX. I have *no idea* how to do the equivalent for ODS.

This is the diff between my test XLSX files:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/472468/165791404-86f08ff9-7f0b-4ece-967d-bd039f9be15c.png">

..and the diff between my test ODS files:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/472468/165791555-8dbb4827-cef2-497b-867f-1eb3be0aac2a.png">

Anyone able to help with the ODS implementation?

2022-04-29 07:45 UTC, jonnott commented
@Slamdunk

2022-06-02 13:13 UTC, faytekin commented
@Slamdunk

2022-06-06 07:11 UTC, Slamdunk commented
@faytekin may you help @jonnott with the ODS implementation?

2022-07-21 14:32 UTC, delameter commented
Fixed broken pipeline in 7f8ff57a90b7453135138e4a595df040c69424ed (made a PR original branch in author's repo).

Also researched a bit about ODS implementation, and it's a lot harder than it seems to be.  I'll cut to the chase, in ODS "height" is the attribute of style, not the attribute of row. I attempted to insert elements describing row style `<style:table-row-properties style:row-height="$$$pt" style:use-optimal-row-height="false"/>` into `table` section before row definition, but they were ignored by Libre (small wonder). Libre itself saves row height like this:

![image](https://user-images.githubusercontent.com/50381946/180238314-85e30b84-a171-4905-b280-69f5c8ee836c.png)

But AFAIK writing row styles is not implemented in current version (only cell styles). It's hard to say how long will it take for someone to fully implement this, if it's even possible considering write-only approach.

At the same time, setting the height of XLSX rows seems to work (the only thing that I can't comprehend is why @jonnott used `string` variable to store the height and not `float`), so how about separating these two features and releasing customizable heights for XLSX only?

2022-07-21 14:34 UTC, jonnott commented
> (the only thing that I can't comprehend is why @jonnott used `string` variable to store the height and not `float`)

@delameter Feel free to change this if you feel `float` would be better.

2022-07-21 14:36 UTC, jonnott commented
> > (the only thing that I can't comprehend is why @jonnott used `string` variable to store the height and not `float`)
> 
> @delameter Feel free to change this if you feel `float` would be better.

I think it was just because the pre-existing `setHeight()` and `getHeight()` (which I reinstated after they had been removed) used `string` for this property.

2022-07-21 14:38 UTC, delameter commented
I also made `Dockerfile` and `docker-compose.yml` for fast tests launching and debugging without fiddling with dependencies, but don't know will it fit in or not. If it's acceptable I can create a separate PR for adding Docker support.

2022-07-21 15:02 UTC, delameter commented
> > > (the only thing that I can't comprehend is why @jonnott used `string` variable to store the height and not `float`)
> > 
> > 
> > @delameter Feel free to change this if you feel `float` would be better.
> 
> I think it was just because the pre-existing `setHeight()` and `getHeight()` (which I reinstated after they had been removed) used `string` for this property.

Well I can assume that it was initially made for possibility to set the height with units, like "15pt" or "2cm",  but then there should be at least some validation mechanism (even if rudimentary) to ensure that internal file markup will not be broken.

2022-07-22 14:15 UTC, jonnott commented
> Well I can assume that it was initially made for possibility to set the height with units, like "15pt" or "2cm",

Yes, I think that's why.

2022-12-10 15:23 UTC, jonnott commented
@Slamdunk Any ideas who might be able to help get this one over the line?

2022-12-12 07:47 UTC, Slamdunk requested changes
I'm ok to merge this without ODS support.

Let's just use native types and we're ok

2022-12-12 07:47 UTC, Slamdunk commented on src/Common/Entity/Row.php
> +    private string $height = '';
```suggestion
    private float $height = 0;
```

2022-12-12 07:47 UTC, Slamdunk commented on src/Common/Entity/Row.php
> +    public function setHeight(string $height): self
```suggestion
    public function setHeight(float $height): self
```

2022-12-12 07:47 UTC, Slamdunk commented on src/Common/Entity/Row.php
> +    public function getHeight(): string
```suggestion
    public function getHeight(): float
```

2022-12-12 14:34 UTC, jonnott commented
Committed those changes @Slamdunk

2022-12-12 14:35 UTC, Slamdunk requested changes
We forgot this one I guess

2022-12-12 14:35 UTC, Slamdunk commented on tests/Writer/XLSX/WriterTest.php
> +        $this->writeToXLSXFile([Row::fromValues(['xlsx--11'])->setHeight('25')], $fileName);
```suggestion
        $this->writeToXLSXFile([Row::fromValues(['xlsx--11'])->setHeight(25)], $fileName);
```

2022-12-12 14:37 UTC, jonnott commented
Fixed test also

2022-12-12 14:39 UTC, Slamdunk requested changes
Coding Standards and Static Analysis must be fixed too

2022-12-12 15:55 UTC, jonnott commented
@Slamdunk I have no idea why the Static Analysis says "Error: Cannot call method getAttribute() on DOMNode|false.". I therefore cannot implement a solution. I can't see how it's got anything to do with this PR specifically.

2022-12-13 07:41 UTC, Slamdunk approved these changes

2022-12-13 07:41 UTC, merged